### ISSUE TITLE
Impossible to import SAS tables

### ISSUE THREAD

**Issue by pierre-lamarche** [pierre-lamarche/Household-Finance-and-Consumption-Survey#2]
At the time being, it is not possible to use package `haven` for the importation into R format.

**Comment by pierre-lamarche** [comment]
https://cran.r-project.org/web/packages/haven/news.html

Possibly the issue is solved with the release of the new version of package `haven`.

**Comment by pierre-lamarche** [comment]
Issue still pending, very likely related to [this issue](https://github.com/WizardMac/ReadStat/issues/21) in readStat package.

**Comment by oliviermeslin** [comment]
@pierre-lamarche : I think `haven` 2.4.0 and after supports binary compression. See [here](https://github.com/WizardMac/ReadStat/issues/21).

**Comment by pierre-lamarche** [comment]
There's nothing time can't solve. Thanks @oliviermeslin
